name: Merge C++ lint

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Format code with clang-format
      run: |
        clang-format -i tb_top.cpp
     #   find . -iname *.cpp -o -iname *.h | xargs clang-format -i
    #    git diff --exit-code  # Fail if there are unformatted files

  #  - name: Build the project
  #    run: |
  #      make  # or your build command